language: julia

os:
  - linux
  # - osx
  # - windows

julia:
  - 1.0
  - 1
  - nightly

notifications:
  email:
    recipients: abel.s.siqueira@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

jobs:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'if Sys.islinux()
      using Pkg; pkg"add Coverage"; using Coverage; Coveralls.submit(Coveralls.process_folder())
    end'